# [status]
# show_size = true
#
# [status.format]
# right = [
#     { field = "size", style = "white" },
#     # You can keep other existing status items here
#     { field = "permissions", style = "white" },
#     { field = "modified", style = "white" }
# ]

[manager]
linemode = "size"
